#!/usr/bin/ruby
require 'net/ssh'

conf_dir = Dir.home() + '/.marcker-compose'
working_dir = Dir.pwd()
if not Dir.exist?(conf_dir) then
  Dir.mkdir(conf_dir)
end
Dir.chdir(conf_dir)

if ARGV[0] == 'setup' then
  ARGV.shift

  provision = <<END_PROVISION_F
#!/bin/bash

echo "deb http://http.debian.net/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list
apt-get update
apt-get install --no-install-recommends -q -o Dpkg::Options::="--force-confold" --force-yes -y \
  docker.io curl vim screen ca-certificates openssl git

gpasswd -a vagrant docker

echo "Installing docker-compose"
curl -k -L -sS https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose
chmod +x /usr/bin/docker-compose
END_PROVISION_F
  provision_f = File.open(conf_dir + '/provision.sh', 'w')
  provision_f.puts provision
  provision_f.close

  vagrant = <<END_VAGRANT_F
Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "debian/jessie64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "#{Dir.home()}", "#{Dir.home()}", nfs: true
  config.vm.network "private_network", ip: "10.9.8.7"
  config.ssh.forward_agent = "true"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--hwvirtex", "on"]
  end

  # Shell provisioning
  config.vm.provision "fix-no-tty", type: "shell" do |s|
      s.privileged = false
      s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end
  config.vm.provision :shell, :path => "provision.sh"
end
END_VAGRANT_F
  vagrant_f = File.open(conf_dir + '/Vagrantfile','w')
  vagrant_f.puts vagrant
  vagrant_f.close

  system("vagrant up")

  ssh_config = `vagrant ssh-config`
  ssh_config_f = File.open(conf_dir + '/ssh_config','w')
  ssh_config_f.puts ssh_config.chomp + "  DynamicForward 3128"
  ssh_config_f.close
elsif ARGV[0] == 'shutdown' then
  ARGV.shift
  system("vagrant halt")
else
  args=ARGV.join(" ")
  Net::SSH.start('default','vagrant', :config => conf_dir + '/ssh_config') do |ssh|
    ssh.exec "cd #{working_dir}; docker-compose #{args}"
  end
end
